# Generated by Django 5.0.4 on 2024-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('FR', 'France'), ('DE', 'Germany'), ('JP', 'Japan'), ('CN', 'China'), ('IN', 'India'), ('BR', 'Brazil'), ('RU', 'Russia'), ('KR', 'South Korea'), ('IT', 'Italy'), ('ES', 'Spain'), ('CA', 'Canada'), ('AU', 'Australia'), ('MX', 'Mexico'), ('ID', 'Indonesia'), ('TR', 'Turkey'), ('NL', 'Netherlands'), ('SA', 'Saudi Arabia'), ('CH', 'Switzerland'), ('AR', 'Argentina'), ('SE', 'Sweden'), ('BE', 'Belgium'), ('AT', 'Austria'), ('NO', 'Norway'), ('PL', 'Poland'), ('TH', 'Thailand'), ('AE', 'United Arab Emirates'), ('SG', 'Singapore'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('EG', 'Egypt'), ('FI', 'Finland'), ('GR', 'Greece'), ('PT', 'Portugal'), ('CZ', 'Czech Republic'), ('IE', 'Ireland'), ('HU', 'Hungary')], default='BR', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
